# Generated by Django 5.1.4 on 2024-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_dashboard', '0002_alter_customusers_bio_alter_project_title_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
